### PR TITLE
Use test-unit-rr

### PR DESCRIPTION
**Pull request by myokoym**
We may want to use test double framework such as [RR](https://github.com/rr/rr).
[test-unit-rr](https://github.com/test-unit/test-unit-rr) is a RR adapter for test-unit.

### CODE REVIEW

**Comment by tricknotes** [comment]
Where do you want to use?

**Comment by myokoym** [comment]
I have not think what to use specifically. Please put this PR on hold.

**Comment by cosmo0920** [comment]
For example, `Faraday`'s README TODO section says that "better stubbing API".
Thus, in this case, `test-unit-rr` usage is ... "I want to use more generic stub APIs in test".
How about you @myokoym ?

But for now, I think that this PR leaves it as-is is better. Don't merge it.

**Comment by myokoym** [comment]
コマンドのテストをするときにクラス単位でモックできるとうれしいかもなーと思いましたが、
いまのところ不要なので保留でおねがいします。

**Comment by okkez** [comment]
filterのテストで使うことにしました。
既い master にマージしたので close します。

**Pull request closed without merging**
