### PR TITLE
Acceptance

### PR DESCRIPTION
**Pull request by tricknotes**
I added API to use from client.
And I'll add some acceptance tests against it.

@okkez @myokoym 
WDYT these API?
* [`DaimonSkycrawlers.register_processor`](https://github.com/bm-sms/daimon-skycrawlers/blob/acceptance/test/fixtures/simple/processor.rb#L6-L8)
* <del>[`DaimonSkycrawlers.run_crawl`](https://github.com/bm-sms/daimon-skycrawlers/blob/acceptance/test/fixtures/simple/crawler.rb#L6)</de>
* [`DaimonSkycrawlers.register_crawler`](https://github.com/bm-sms/daimon-skycrawlers/blob/acceptance/test/fixtures/simple/crawler.rb#L8)

These are just draft.
I want any feedback :sunny:

### CODE REVIEW

**Comment by okkez** [comment]
Crawler may have complex setup.

**Comment by tricknotes** [comment]
I think so too, for now.

**Comment by tricknotes** [comment]
I updated a crawler API. [`DaimonSkycrawlers.register_crawler`](https://github.com/bm-sms/daimon-skycrawlers/blob/acceptance/test/fixtures/simple/crawler.rb#L8)
In favor of https://github.com/bm-sms/daimon-skycrawlers/commit/0ed0d1c862db1d8ba9e6a44e24f99391dcb15268#commitcomment-15576734.

**Comment by tricknotes** [comment]
How to use:

* Processor
```
$ cd test/fixtures/simple
$ bundle exec ruby processor.rb
```

* Crawler
```
$ cd test/fixtures/simple
$ bundle exec ruby crawler.rb
```

**Comment by tricknotes** [comment]
This PR is now review ready.

**Comment by okkez** [comment]
:+1:

**Pull request merged**
